#!/bin/bash

echo "🌐 Ngrok Setup for Solana HTTP Server"
echo "======================================"
echo ""
echo "📋 Steps to get your shareable link:"
echo ""
echo "1. 📝 Sign up for ngrok (free): https://dashboard.ngrok.com/signup"
echo "2. 🔑 Get your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken"
echo "3. 🔧 Run: ngrok config add-authtoken YOUR_TOKEN"
echo "4. 🚀 Run: ngrok http 3000"
echo ""
echo "🎯 Your Solana server is running on: http://127.0.0.1:3000"
echo ""
echo "📋 Available endpoints (will work with ngrok URL too):"
echo "  POST /keypair        - Generate a new Solana keypair"
echo "  POST /token/create   - Create SPL token mint instruction"
echo "  POST /token/mint     - Create mint tokens instruction"
echo "  POST /message/sign   - Sign a message with a private key"
echo "  POST /message/verify - Verify a signed message"
echo "  POST /send/sol       - Create SOL transfer instruction"
echo "  POST /send/token     - Create SPL token transfer instruction"
echo ""
echo "💡 Example curl command (replace NGROK_URL with your ngrok URL):"
echo "curl -X POST https://YOUR_NGROK_URL.ngrok.io/keypair"
echo ""
echo "🔗 After setting up ngrok, you'll get a URL like: https://abc123.ngrok.io"
echo "   This URL will be accessible from anywhere on the internet!"
